on: [push]

jobs:
  test_job:
    runs-on: ubuntu-latest
    name: Test installation.
    steps:
      - uses: actions/checkout@v3

      - id: install-version
        uses: diku-dk/install-mlton@HEAD
        with:
          version: '20210117'
      - id: install-no-version
        uses: diku-dk/install-mlton@HEAD
      - id: install-latest
        uses: diku-dk/install-mlton@HEAD
        with:
          version: 'latest'
