on: [push, workflow_dispatch]

jobs:
  test_job:
    runs-on: ubuntu-latest
    name: Test installation.
    steps:
      - uses: actions/checkout@v3

      - name: Install 20210117
        uses: diku-dk/install-mlton@HEAD
        with:
          version: '20210117'

      - name: Install 20241230
        uses: diku-dk/install-mlton@HEAD
        with:
          version: '20241230'

      - name: Install unspecified version
        uses: diku-dk/install-mlton@HEAD

      - name: Install latest version
        uses: diku-dk/install-mlton@HEAD
        with:
          version: 'latest'
